spring:
  redis:
    host: ${REDIS_HOST:10.203.72.183}
    port: ${REDIS_PORT:6379}
    ##password: ${REDIS_PASSWORD:}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:10.203.72.183}:${DATASOURCE_PORT:3306}/sc_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
  mvc:
    throw-exception-if-no-handler-found: true

  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
minemall:
  security:
    code:
      image:
        expireIn: 180
        url: /auth/register,/auth/submitResetPwdEmail,/auth/code/sms
      sms:
        expireIn: 600
        url: /uac/auth/submitResetPwdPhone
        mobileMaxSendCount: 1
        ipMaxSendCount: 2
        totalMaxSendCount: 3