spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:192.168.1.103}:${DATASOURCE_PORT:3306}/mall_order?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
#  cloud:
#    stream:
#      bindings:
#        hystrixStreamOutput:
#          destination: "turbineStreamInput"
#  zipkin:
#    sender:
#      type: rabbit
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1.0
#    feign:
#      enabled: true
#      processor:
#        enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "3MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:com/springboot/cloud/**/mapper/*Mapper.xml
  type-aliases-package: com.springboot.cloud.**.po
  configuration:
    map-underscore-to-camel-case: true
mall:
  alipay:
    callback:
      url: http://http://localhost:8443/mall-order/pay/alipayCallback
    qrCode:
      pcPath: /data/file/qrCode/alipay
      qiniuPath: alipay/QRCode/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#feign:
#  hystrix:
#    enabled: true
#hystrix:
#  stream:
#    queue:
#      destination: "turbineStreamInput"
