spring:
  redis:
    host: ${REDIS_HOST:192.168.1.103}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 300
    #password: ${REDIS_PASSWORD:123456}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:192.168.1.103}:${DATASOURCE_PORT:3306}/sc_admin?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8
#  resources:
#    add-mappings: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)
