server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: ribbon-consumer
  rabbitmq:
    host: ${RABBIT_MQ_HOST:10.203.72.183}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:mine}
    password: ${RABBIT_MQ_PASSWORD:mine}
    virtual-host: ${RABBIT_MQ_VIRTUAL:/mine}
  cloud:
    stream:
      bindings:
        hystrixStreamOutput:
          destination: "turbineStreamInput"
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0

  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8

logging:
  level:
    org.springframework.web: debug
  path: /data/logs/MineCloud/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'