server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  profiles:
    active: dev
  application:
    name: config-server
  rabbitmq:
#    host: ${RABBIT_MQ_HOST:10.203.72.183}
    host: ${RABBIT_MQ_HOST:192.168.1.103}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:mine}
    password: ${RABBIT_MQ_PASSWORD:mine}
    virtual-host: ${RABBIT_MQ_VIRTUAL:/mine}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Young-Guiji/MineCloud.git
          searchPaths: config-repo
          proxy:
            https:
              host: 10.191.113.100
              password: jayJAY11.
              port: 8002
              username: xieboyun-001

management:
  endpoints:
    web:
      exposure:
        include: '*'