server:
  port: 31003

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/
spring:
  profiles:
    active: dev
  application:
    name: mall-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:10.203.72.183}:${DATASOURCE_PORT:3306}/mall_order?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:10.203.72.183}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:mine}
    password: ${RABBIT_MQ_PASSWORD:mine}
    virtual-host: ${RABBIT_MQ_VIRTUAL:/mine}
#  cloud:
#    stream:
#      bindings:
#        hystrixStreamOutput:
#          destination: "turbineStreamInput"
#  zipkin:
#    sender:
#      type: rabbit
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1.0
#    feign:
#      enabled: true
#      processor:
#        enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "3MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:com/springboot/cloud/**/mapper/*Mapper.xml
  type-aliases-package: com.springboot.cloud.**.po
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.cloud.sleuth: debug
  path: /data/logs/MineCloud/
  file:
    max-size: 1GB
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#feign:
#  hystrix:
#    enabled: true
#hystrix:
#  stream:
#    queue:
#      destination: "turbineStreamInput"